const Images = {
  '1.jpg': require('../../assets/images/1.jpg'),
  '3.jpg': require('../../assets/images/3.jpg'),
  '5.jpg': require('../../assets/images/5.jpg'),
  '6.jpg': require('../../assets/images/6.jpg'),
  '8.jpg': require('../../assets/images/8.jpg'),
  '9.jpg': require('../../assets/images/9.jpg'),
  '12.jpg': require('../../assets/images/12.jpg'),
  '14.jpg': require('../../assets/images/14.jpg'),
  '16.jpg': require('../../assets/images/16.jpg'),
  '16-2.jpg': require('../../assets/images/16-2.jpg'),
  '17.jpg': require('../../assets/images/17.jpg'),
  '20.jpg': require('../../assets/images/20.jpg'),
  '21.jpg': require('../../assets/images/21.jpg'),
  '22.jpg': require('../../assets/images/22.jpg'),
  '23.jpg': require('../../assets/images/23.jpg'),
  '24.jpg': require('../../assets/images/24.jpg'),
  '25.jpg': require('../../assets/images/25.jpg'),
  '27.jpg': require('../../assets/images/27.jpg'),
  '28.jpg': require('../../assets/images/28.jpg'),
  '30.jpg': require('../../assets/images/30.jpg'),
  '31.jpg': require('../../assets/images/31.jpg'),
  '34.jpg': require('../../assets/images/34.jpg'),
  '35.jpg': require('../../assets/images/35.jpg'),
  '36.jpg': require('../../assets/images/36.jpg'),
  '37.jpg': require('../../assets/images/37.jpg'),
  '38.jpg': require('../../assets/images/38.jpg'),
  '39.jpg': require('../../assets/images/39.jpg'),
  '43.jpg': require('../../assets/images/43.jpg'),
  '44.jpg': require('../../assets/images/44.jpg'),
  '45.jpg': require('../../assets/images/45.jpg'),
  '47.jpg': require('../../assets/images/47.jpg'),
  '49.jpg': require('../../assets/images/49.jpg'),
  '50.jpg': require('../../assets/images/50.jpg'),
  '50-2.jpg': require('../../assets/images/50-2.jpg'),
  '51.jpg': require('../../assets/images/51.jpg'),
  '52.jpg': require('../../assets/images/52.jpg'),
  '53.jpg': require('../../assets/images/53.jpg'),
  '54.jpg': require('../../assets/images/54.jpg'),
  '55.jpg': require('../../assets/images/55.jpg'),
};

export default Images;
